# Form implementation generated from reading ui file 'C:\Tools\a\Git\Project\dobtow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(415, 374)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.l = QtWidgets.QLabel(parent=Form)
        self.l.setObjectName("l")
        self.verticalLayout.addWidget(self.l)
        self.le = QtWidgets.QLineEdit(parent=Form)
        self.le.setObjectName("le")
        self.verticalLayout.addWidget(self.le)
        self.l1 = QtWidgets.QLabel(parent=Form)
        self.l1.setObjectName("l1")
        self.verticalLayout.addWidget(self.l1)
        self.le1 = QtWidgets.QLineEdit(parent=Form)
        self.le1.setObjectName("le1")
        self.verticalLayout.addWidget(self.le1)
        self.l2 = QtWidgets.QLabel(parent=Form)
        self.l2.setObjectName("l2")
        self.verticalLayout.addWidget(self.l2)
        self.le2 = QtWidgets.QLineEdit(parent=Form)
        self.le2.setObjectName("le2")
        self.verticalLayout.addWidget(self.le2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.l3 = QtWidgets.QLabel(parent=Form)
        self.l3.setObjectName("l3")
        self.verticalLayout_2.addWidget(self.l3)
        self.le3 = QtWidgets.QLineEdit(parent=Form)
        self.le3.setObjectName("le3")
        self.verticalLayout_2.addWidget(self.le3)
        self.l4 = QtWidgets.QLabel(parent=Form)
        self.l4.setObjectName("l4")
        self.verticalLayout_2.addWidget(self.l4)
        self.le4 = QtWidgets.QLineEdit(parent=Form)
        self.le4.setObjectName("le4")
        self.verticalLayout_2.addWidget(self.le4)
        self.l5 = QtWidgets.QLabel(parent=Form)
        self.l5.setObjectName("l5")
        self.verticalLayout_2.addWidget(self.l5)
        self.le5 = QtWidgets.QLineEdit(parent=Form)
        self.le5.setObjectName("le5")
        self.verticalLayout_2.addWidget(self.le5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Новый товар"))
        self.l.setText(_translate("Form", "Введите имя товара:"))
        self.l1.setText(_translate("Form", "Введите тип товара:"))
        self.l2.setText(_translate("Form", "Введите год выпуска:"))
        self.l3.setText(_translate("Form", "Введите качество:"))
        self.l4.setText(_translate("Form", "Введите количество:"))
        self.l5.setText(_translate("Form", "Введите название изображения:"))
        self.pushButton.setText(_translate("Form", "Добавить"))
