# Form implementation generated from reading ui file 'C:\Tools\a\Git\Project\password.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl = QtWidgets.QLabel(parent=Form)
        self.lbl.setObjectName("lbl")
        self.verticalLayout.addWidget(self.lbl)
        self.le = QtWidgets.QLineEdit(parent=Form)
        self.le.setObjectName("le")
        self.verticalLayout.addWidget(self.le)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vp = QtWidgets.QPushButton(parent=Form)
        self.vp.setObjectName("vp")
        self.horizontalLayout.addWidget(self.vp)
        self.btn = QtWidgets.QPushButton(parent=Form)
        self.btn.setObjectName("btn")
        self.horizontalLayout.addWidget(self.btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Мебель-Р-Вход"))
        self.lbl.setText(_translate("Form", "Введите пароль:"))
        self.vp.setText(_translate("Form", "Вход"))
        self.btn.setText(_translate("Form", "Выход"))
