# Form implementation generated from reading ui file 'C:\Tools\a\Git\Project\uwtow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l = QtWidgets.QLabel(parent=Form)
        self.l.setObjectName("l")
        self.verticalLayout.addWidget(self.l)
        self.le = QtWidgets.QLineEdit(parent=Form)
        self.le.setObjectName("le")
        self.verticalLayout.addWidget(self.le)
        self.l1 = QtWidgets.QLabel(parent=Form)
        self.l1.setObjectName("l1")
        self.verticalLayout.addWidget(self.l1)
        self.le1 = QtWidgets.QLineEdit(parent=Form)
        self.le1.setObjectName("le1")
        self.verticalLayout.addWidget(self.le1)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Увеличить склад товара"))
        self.l.setText(_translate("Form", "Введите id товара:"))
        self.l1.setText(_translate("Form", "Введите кол-во товара:"))
        self.pushButton.setText(_translate("Form", "Добавить"))
